name: Deploy Flutter Web to GitHub Pages (FVM)

on:
  push:
    branches: [master] # or [main] depending on your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Flutter with FVM
        uses: subosito/flutter-action@v2
        with:
          flutter-version-file: .fvm/fvm_config.json  # Automatically uses FVM version

      - run: flutter pub get
      - run: flutter build web --base-href=/developerkits.github.io/  # Replace with your repo name

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
